# version: "3.9"

services:
  api:
    image: 726101441058.dkr.ecr.ap-northeast-1.amazonaws.com/minkan:latest # イメージ名
    container_name: minkan-api # 起動後のコンテナ名
    ports:
      - "8080:8080" # ホスト:コンテナ
    env_file:
      - .env
    environment:
      PORT: ":8080"
    restart: unless-stopped # コンテナが docker stop以外で 異常終了したら自動で再起動
